### ISSUE TITLE
pom.xml contains unused dependencies 

### ISSUE THREAD

**Issue by ostret** [NataliiaCherepushchak/PrestaShop#1]
First, let's remove <artifactId>oleg_decik</artifactId>
This is not nice 

Second thing is that if you add dependencies that you don't use it will increase build time 
So please remove everything that is not used

Only add dependant together with code that uses the lib

And don't commit directly to master

**Comment by ostret** [comment]
BTW, there are several broken dependencies:
![image](https://user-images.githubusercontent.com/20928408/68137365-861b6980-ff2f-11e9-915f-c39f43ab25ce.png)

**Comment by Oleg-Decik** [comment]
I know, but Ihor said that all this dependencies will be usefull, oleg_decik will be corrected

**Comment by ostret** [comment]
resolved
